In [1]:
import os
for dirname, _, filenames in os.walk('/content/drive/MyDrive/NLP_Data'):
  for filename in filenames:
    print(os.path.join(dirname, filename))

/content/drive/MyDrive/NLP_Data/train_sentences.txt
/content/drive/MyDrive/NLP_Data/data.json
/content/drive/MyDrive/NLP_Data/train_sentences.gdoc


In [2]:
import json
def read_vocab(path: str)-> dict:
  with open(path) as json_file:
    data = json.load(json_file)
    return data

In [3]:
import collections
vocab = read_vocab('/content/drive/MyDrive/NLP_Data/data.json')
sorted_vocab = sorted(vocab.items(), key=lambda kv: kv[1])
sorted_dict = collections.OrderedDict(sorted_vocab)

In [4]:
vocab

{'Homarus': 0,
 'gammarus': 1,
 ',': 2,
 'known': 3,
 'as': 4,
 'the': 5,
 'European': 6,
 'lobster': 7,
 'or': 8,
 'common': 9,
 'is': 10,
 'a': 11,
 'species': 12,
 'of': 13,
 '': 14,
 'from': 15,
 'eastern': 16,
 'Atlantic': 17,
 'Ocean': 18,
 'Mediterranean': 19,
 'Sea': 20,
 'and': 21,
 'parts': 22,
 'Black': 23,
 'It': 24,
 'closely': 25,
 'related': 26,
 'to': 27,
 'American': 28,
 'H': 29,
 'americanus': 30,
 'may': 31,
 'grow': 32,
 'length': 33,
 '60': 34,
 'cm': 35,
 '(': 36,
 '24': 37,
 'in': 38,
 ')': 39,
 'mass': 40,
 '6': 41,
 'kilograms': 42,
 '13': 43,
 'lb': 44,
 'bears': 45,
 'conspicuous': 46,
 'pair': 47,
 'claws': 48,
 'In': 49,
 'life': 50,
 'lobsters': 51,
 'are': 52,
 'blue': 53,
 'only': 54,
 'becoming': 55,
 '"': 56,
 'red': 57,
 'on': 58,
 'cooking': 59,
 'Mating': 60,
 'occurs': 61,
 'summer': 62,
 'producing': 63,
 'eggs': 64,
 'which': 65,
 'carried': 66,
 'by': 67,
 'females': 68,
 'for': 69,
 'up': 70,
 'year': 71,
 'before': 72,
 'hatching': 73,
 'into

In [5]:
def read_sentences(path: str) -> [str]:
  with open(path, 'r') as f:
    sentences = f.read().split('\n')
    return sentences

In [6]:
sentences = read_sentences('/content/drive/MyDrive/NLP_Data/train_sentences.txt')

In [7]:
sentences

['Homarus gammarus , known as the European lobster or common lobster , is a species of  lobster from the eastern Atlantic Ocean , Mediterranean Sea and parts of the Black Sea',
 'It is closely related to the American lobster , H',
 'americanus',
 'It may grow to a length of 60 cm ( 24 in ) and a mass of 6 kilograms ( 13 lb ) , and bears a conspicuous pair of claws',
 'In life , the lobsters are blue , only becoming " lobster red " on cooking',
 'Mating occurs in the summer , producing eggs which are carried by the females for up to a year before hatching into  larvae',
 'Homarus gammarus is a highly esteemed food , and is widely caught using lobster pots , mostly around the British Isles',
 'Description',
 'Homarus gammarus is a large  , with a body length up to 60 centimetres ( 24 in ) and weighing up to 5 – 6 kilograms ( 11 – 13 lb ) , although the lobsters caught in lobster pots are usually 23 – 38 cm ( 9 – 15 in ) long and weigh 0 @',
 'Like other crustaceans , lobsters have a hard

In [8]:
sentences.remove(sentences[-1])

In [9]:
def split_words_by_sentences(sentences: [str]) -> [[str]]:
  list_words_by_sentences = [sentence.split(" ") for sentence in sentences]
  return list_words_by_sentences

In [10]:
list_words_by_sentences = split_words_by_sentences(sentences)

In [11]:
list_words_by_sentences

[['Homarus',
  'gammarus',
  ',',
  'known',
  'as',
  'the',
  'European',
  'lobster',
  'or',
  'common',
  'lobster',
  ',',
  'is',
  'a',
  'species',
  'of',
  '',
  'lobster',
  'from',
  'the',
  'eastern',
  'Atlantic',
  'Ocean',
  ',',
  'Mediterranean',
  'Sea',
  'and',
  'parts',
  'of',
  'the',
  'Black',
  'Sea'],
 ['It',
  'is',
  'closely',
  'related',
  'to',
  'the',
  'American',
  'lobster',
  ',',
  'H'],
 ['americanus'],
 ['It',
  'may',
  'grow',
  'to',
  'a',
  'length',
  'of',
  '60',
  'cm',
  '(',
  '24',
  'in',
  ')',
  'and',
  'a',
  'mass',
  'of',
  '6',
  'kilograms',
  '(',
  '13',
  'lb',
  ')',
  ',',
  'and',
  'bears',
  'a',
  'conspicuous',
  'pair',
  'of',
  'claws'],
 ['In',
  'life',
  ',',
  'the',
  'lobsters',
  'are',
  'blue',
  ',',
  'only',
  'becoming',
  '"',
  'lobster',
  'red',
  '"',
  'on',
  'cooking'],
 ['Mating',
  'occurs',
  'in',
  'the',
  'summer',
  ',',
  'producing',
  'eggs',
  'which',
  'are',
  'carried',

In [12]:
maxlen = len(max(list_words_by_sentences, key=len))

In [13]:
maxlen

62

In [14]:
def add_padding(list_words_by_sentences: [[str]]) -> [[str]]:
  list_words_by_sentences_has_padding = list_words_by_sentences
  for i, sentence in enumerate(list_words_by_sentences_has_padding):
    sentence_len = len(sentence)
    if sentence_len < maxlen:
      for j in range(maxlen - sentence_len):
        list_words_by_sentences_has_padding[i].append(" ")
  return list_words_by_sentences_has_padding

In [15]:
list_words_by_sentences = add_padding(list_words_by_sentences)

In [16]:
for sentence in list_words_by_sentences:
  print(len(sentence))
  print(sentence)

62
['Homarus', 'gammarus', ',', 'known', 'as', 'the', 'European', 'lobster', 'or', 'common', 'lobster', ',', 'is', 'a', 'species', 'of', '', 'lobster', 'from', 'the', 'eastern', 'Atlantic', 'Ocean', ',', 'Mediterranean', 'Sea', 'and', 'parts', 'of', 'the', 'Black', 'Sea', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
62
['It', 'is', 'closely', 'related', 'to', 'the', 'American', 'lobster', ',', 'H', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
62
['americanus', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 

In [17]:
def generate_input_target_seq(list_words_by_sentences: [[str]]) -> ([[str]], [[str]]):
  input_seq = []
  target_seq = []
  for i in range(len(list_words_by_sentences)):
      input_seq.append(list_words_by_sentences[i][:-1])
      target_seq.append(list_words_by_sentences[i][1:])
      print("Input Sequence: {}\nTarget Sequence: {}".format(input_seq[i], target_seq[i]))
  return (input_seq, target_seq)

In [18]:
input_seq, target_seq = generate_input_target_seq(list_words_by_sentences)

Input Sequence: ['Homarus', 'gammarus', ',', 'known', 'as', 'the', 'European', 'lobster', 'or', 'common', 'lobster', ',', 'is', 'a', 'species', 'of', '', 'lobster', 'from', 'the', 'eastern', 'Atlantic', 'Ocean', ',', 'Mediterranean', 'Sea', 'and', 'parts', 'of', 'the', 'Black', 'Sea', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
Target Sequence: ['gammarus', ',', 'known', 'as', 'the', 'European', 'lobster', 'or', 'common', 'lobster', ',', 'is', 'a', 'species', 'of', '', 'lobster', 'from', 'the', 'eastern', 'Atlantic', 'Ocean', ',', 'Mediterranean', 'Sea', 'and', 'parts', 'of', 'the', 'Black', 'Sea', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
Input Sequence: ['It', 'is', 'closely', 'related', 'to', 'the', 'American', 'lobster', ',', 'H', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '

In [19]:
len_sentences = len(sentences)
len_vocab = len(vocab.keys())
print(len_sentences)
print(len_vocab)

225
1160


In [20]:
import torch
import torch.nn as nn
import numpy as np
embeds = nn.Embedding(len_vocab, maxlen)

In [21]:
def embedding_input_seq(input: [[str]]):
    input_seq = input
    for i, sentence in enumerate(input_seq):
      for j, words in enumerate(sentence):
        if words in vocab.keys():
          tensor = torch.tensor(vocab[words], dtype=torch.long)
          input_seq[i][j] = embeds(tensor).detach().numpy()
        else:
          key = words.lower()
          tensor = torch.tensor(vocab[key], dtype=torch.long)
          input_seq[i][j] = embeds(tensor).detach().numpy()
    return np.array(input_seq)

In [22]:
input_seq = embedding_input_seq(input_seq)

In [23]:
input_seq

array([[[ 0.3441918 ,  0.2279963 ,  0.30777347, ...,  0.2772978 ,
         -0.8518749 ,  1.0583613 ],
        [-0.4564641 ,  0.04343298,  1.1899201 , ..., -1.2306931 ,
         -0.16412441, -1.0677115 ],
        [ 1.2038819 , -1.5243388 ,  1.7063402 , ..., -0.53317875,
          0.46365705,  1.3293318 ],
        ...,
        [ 0.8431873 , -0.7913686 ,  0.06106792, ...,  0.5240572 ,
          1.8643258 , -0.3927498 ],
        [ 0.8431873 , -0.7913686 ,  0.06106792, ...,  0.5240572 ,
          1.8643258 , -0.3927498 ],
        [ 0.8431873 , -0.7913686 ,  0.06106792, ...,  0.5240572 ,
          1.8643258 , -0.3927498 ]],

       [[ 0.08021434,  1.0812825 ,  0.8785903 , ...,  0.614913  ,
         -1.6492707 , -0.42767662],
        [-3.4072175 , -0.95830697, -0.25762078, ..., -0.02377111,
         -0.03563169, -0.75431204],
        [ 1.6486659 ,  1.3560247 ,  0.44865847, ...,  0.9753864 ,
         -0.02846077,  0.5627671 ],
        ...,
        [ 0.8431873 , -0.7913686 ,  0.06106792, ...,  

In [24]:
def embedding_target_seq(target: [[str]]):
  target_seq = target
  for i, sentence in enumerate(target_seq):
    for j, words in enumerate(sentence):
      if words in vocab.keys():
        target_seq[i][j] = vocab[words]
      else:
        key = words.lower()
        target_seq[i][j] = vocab[key]
  return np.array(target_seq)

In [25]:
target_seq = embedding_target_seq(target_seq)

In [26]:
target_seq

array([[   1,    2,    3, ..., 1159, 1159, 1159],
       [  10,   25,   26, ..., 1159, 1159, 1159],
       [1159, 1159, 1159, ..., 1159, 1159, 1159],
       ...,
       [ 659,  508,  333, ..., 1159, 1159, 1159],
       [ 126,  575,  684, ..., 1159, 1159, 1159],
       [ 620,    4,  572, ..., 1159, 1159, 1159]])

In [27]:
input_seq = torch.from_numpy(input_seq)

In [28]:
input_seq

tensor([[[ 0.3442,  0.2280,  0.3078,  ...,  0.2773, -0.8519,  1.0584],
         [-0.4565,  0.0434,  1.1899,  ..., -1.2307, -0.1641, -1.0677],
         [ 1.2039, -1.5243,  1.7063,  ..., -0.5332,  0.4637,  1.3293],
         ...,
         [ 0.8432, -0.7914,  0.0611,  ...,  0.5241,  1.8643, -0.3927],
         [ 0.8432, -0.7914,  0.0611,  ...,  0.5241,  1.8643, -0.3927],
         [ 0.8432, -0.7914,  0.0611,  ...,  0.5241,  1.8643, -0.3927]],

        [[ 0.0802,  1.0813,  0.8786,  ...,  0.6149, -1.6493, -0.4277],
         [-3.4072, -0.9583, -0.2576,  ..., -0.0238, -0.0356, -0.7543],
         [ 1.6487,  1.3560,  0.4487,  ...,  0.9754, -0.0285,  0.5628],
         ...,
         [ 0.8432, -0.7914,  0.0611,  ...,  0.5241,  1.8643, -0.3927],
         [ 0.8432, -0.7914,  0.0611,  ...,  0.5241,  1.8643, -0.3927],
         [ 0.8432, -0.7914,  0.0611,  ...,  0.5241,  1.8643, -0.3927]],

        [[ 0.0612, -0.0609, -0.3105,  ..., -0.3818, -0.5579, -0.8567],
         [ 0.8432, -0.7914,  0.0611,  ...,  0

In [29]:
input_seq.shape

torch.Size([225, 61, 62])

In [30]:
target_seq = torch.Tensor(target_seq)

In [31]:
target_seq

tensor([[1.0000e+00, 2.0000e+00, 3.0000e+00,  ..., 1.1590e+03, 1.1590e+03,
         1.1590e+03],
        [1.0000e+01, 2.5000e+01, 2.6000e+01,  ..., 1.1590e+03, 1.1590e+03,
         1.1590e+03],
        [1.1590e+03, 1.1590e+03, 1.1590e+03,  ..., 1.1590e+03, 1.1590e+03,
         1.1590e+03],
        ...,
        [6.5900e+02, 5.0800e+02, 3.3300e+02,  ..., 1.1590e+03, 1.1590e+03,
         1.1590e+03],
        [1.2600e+02, 5.7500e+02, 6.8400e+02,  ..., 1.1590e+03, 1.1590e+03,
         1.1590e+03],
        [6.2000e+02, 4.0000e+00, 5.7200e+02,  ..., 1.1590e+03, 1.1590e+03,
         1.1590e+03]])

In [ ]:
target_seq.shape

torch.Size([225, 61])

In [32]:
from typing import *
from pathlib import Path

In [33]:
from enum import IntEnum
class Dim(IntEnum):
    batch = 0
    seq = 1
    feature = 2

In [34]:
class NaiveLSTM(nn.Module):
    def __init__(self, input_sz: int, output_sz: int, hidden_sz: int):
        super().__init__()
        self.input_size = input_sz
        self.hidden_size = hidden_sz


        self.Wf = Parameter(torch.Tensor(input_sz+hidden_sz, hidden_sz))
        self.bf = Parameter(torch.Tensor(hidden_sz))

        self.Wi = Parameter(torch.Tensor(input_sz+hidden_sz, hidden_sz))
        self.bi = Parameter(torch.Tensor(hidden_sz))

        self.Wc = Parameter(torch.Tensor(input_sz+hidden_sz, hidden_sz))
        self.bc = Parameter(torch.Tensor(hidden_sz))

        self.Wo = Parameter(torch.Tensor(input_sz+hidden_sz, hidden_sz))
        self.bo = Parameter(torch.Tensor(hidden_sz))

        self.fc = nn.Linear(hidden_sz, output_sz)
        self.init_weights()
    
    def init_weights(self):
        for p in self.parameters():
            if p.data.ndimension() >= 2:
                nn.init.xavier_uniform_(p.data)
            else:
                nn.init.zeros_(p.data)
        
    

    def forward(self, x: torch.Tensor, 
                init_states: Optional[Tuple[torch.Tensor, torch.Tensor]]=None
               ) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:

        batch_sz, seq_sz, _ = x.size()
        hidden_seq = []

        if init_states is None:
            ht = torch.zeros((batch_sz,self.hidden_size)).to(x.device)
            Ct = torch.zeros((batch_sz,self.hidden_size)).to(x.device)
        else:
            ht, Ct = init_states
        for t in range(seq_sz): 
            xt = x[:, t, :]
            hx_concat = torch.cat((ht,xt),dim=1)
            ft = torch.sigmoid(hx_concat @ self.Wf + self.bf)
            it = torch.sigmoid(hx_concat @ self.Wi + self.bi)
            Ct_candidate = torch.tanh(hx_concat @ self.Wc + self.bc)
            ot = torch.sigmoid(hx_concat @ self.Wo + self.bo)
            Ct = ft * Ct + it * Ct_candidate
            ht = ot * torch.tanh(Ct)
            hidden_seq.append(ht.unsqueeze(Dim.batch))
        hidden_seq = torch.cat(hidden_seq, dim=Dim.batch)
        out = hidden_seq.transpose(Dim.batch, Dim.seq).contiguous().view(-1, self.hidden_size)
        out = self.fc(out)
        return out, (ht, Ct)

In [35]:
is_cuda = torch.cuda.is_available()

if is_cuda:
    device = torch.device("cuda")
    print("GPU is available")
else:
    device = torch.device("cpu")
    print("GPU not available, CPU used")

GPU is available


In [36]:
from torch.nn import Parameter

In [37]:
rnnModel = NaiveLSTM(input_sz=62, output_sz=1160, hidden_sz=62)
rnnModel = rnnModel.to(device)

n_epochs = 100
lr=0.01

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(rnnModel.parameters(), lr=lr)

In [38]:
input_seq = input_seq.to(device)

for epoch in range(1, n_epochs + 1):
    optimizer.zero_grad() 
    input_seq = input_seq.to(device)
    output, (hidden, cell) = rnnModel(input_seq)
    output = output.to(device)
    target_seq = target_seq.to(device)
    loss = criterion(output, target_seq.view(-1).long())
    loss.backward() 
    optimizer.step() 
    
    if epoch%10 == 0:
        print('Epoch: {}/{}.............'.format(epoch, n_epochs), end=' ')
        print("Loss: {:.4f}".format(loss.item()))

Epoch: 10/100............. Loss: 2.0947
Epoch: 20/100............. Loss: 1.7026
Epoch: 30/100............. Loss: 1.5480
Epoch: 40/100............. Loss: 1.4123
Epoch: 50/100............. Loss: 1.2746
Epoch: 60/100............. Loss: 1.1385
Epoch: 70/100............. Loss: 1.0067
Epoch: 80/100............. Loss: 0.8817
Epoch: 90/100............. Loss: 0.7642
Epoch: 100/100............. Loss: 0.6585


In [39]:
class MogLSTM(nn.Module):
    def __init__(self, input_sz: int, output_sz: int, hidden_sz: int, mog_iterations: int):
        super().__init__()
        self.input_size = input_sz
        self.hidden_size = hidden_sz
        self.mog_iterations = mog_iterations

        self.Wih = Parameter(torch.Tensor(input_sz, hidden_sz * 4))
        self.Whh = Parameter(torch.Tensor(hidden_sz, hidden_sz * 4))
        self.bih = Parameter(torch.Tensor(hidden_sz * 4))
        self.bhh = Parameter(torch.Tensor(hidden_sz * 4))

        self.Q = Parameter(torch.Tensor(hidden_sz,input_sz))
        self.R = Parameter(torch.Tensor(input_sz,hidden_sz))
        self.fc = nn.Linear(hidden_sz, output_sz)
        self.init_weights()
    
    def init_weights(self):
        for p in self.parameters():
            if p.data.ndimension() >= 2:
                nn.init.xavier_uniform_(p.data)
            else:
                nn.init.zeros_(p.data)

    def mogrify(self,xt,ht):
      for i in range(1,self.mog_iterations+1):
        if (i % 2 == 0):
          ht = (2*torch.sigmoid(xt @ self.R)) * ht
        else:
          xt = (2*torch.sigmoid(ht @ self.Q)) * xt
      return xt, ht

   
    def forward(self, x: torch.Tensor, 
                init_states: Optional[Tuple[torch.Tensor, torch.Tensor]]=None
               ) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:

        batch_sz, seq_sz, _ = x.size()
        hidden_seq = []

        if init_states is None:
            ht = torch.zeros((batch_sz,self.hidden_size)).to(x.device)
            Ct = torch.zeros((batch_sz,self.hidden_size)).to(x.device)
        else:
            ht, Ct = init_states
        for t in range(seq_sz):
            xt = x[:, t, :]
            xt, ht = self.mogrify(xt,ht)
            gates = (xt @ self.Wih + self.bih) + (ht @ self.Whh + self.bhh)
            ingate, forgetgate, cellgate, outgate = gates.chunk(4, 1)

            ft = torch.sigmoid(forgetgate)
            it = torch.sigmoid(ingate)
            Ct_candidate = torch.tanh(cellgate)
            ot = torch.sigmoid(outgate)
            
            Ct = (ft * Ct) + (it * Ct_candidate)
            ht = ot * torch.tanh(Ct)

            hidden_seq.append(ht.unsqueeze(Dim.batch))
        hidden_seq = torch.cat(hidden_seq, dim=Dim.batch)
        out = hidden_seq.transpose(Dim.batch, Dim.seq).contiguous().view(-1, self.hidden_size)
        out = self.fc(out)
        return out, (ht, Ct)

In [40]:
mogLSTM = MogLSTM(input_sz=62, output_sz=1160, hidden_sz=62, mog_iterations=5)
mogLSTM = mogLSTM.to(device)

n_epochs = 100
lr=0.01

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(mogLSTM.parameters(), lr=lr)

In [41]:
input_seq = input_seq.to(device)

for epoch in range(1, n_epochs + 1):
    optimizer.zero_grad() 
    input_seq = input_seq.to(device)
    output, (hidden, cell) = mogLSTM(input_seq)
    output = output.to(device)
    target_seq = target_seq.to(device)
    loss = criterion(output, target_seq.view(-1).long())
    loss.backward() 
    optimizer.step() 
    
    if epoch%10 == 0:
        print('Epoch: {}/{}.............'.format(epoch, n_epochs), end=' ')
        print("Loss: {:.4f}".format(loss.item()))

Epoch: 10/100............. Loss: 2.2852
Epoch: 20/100............. Loss: 1.6418
Epoch: 30/100............. Loss: 1.4612
Epoch: 40/100............. Loss: 1.2763
Epoch: 50/100............. Loss: 1.0817
Epoch: 60/100............. Loss: 0.8916
Epoch: 70/100............. Loss: 0.7158
Epoch: 80/100............. Loss: 0.5719
Epoch: 90/100............. Loss: 0.4708
Epoch: 100/100............. Loss: 0.3729
